package com.fariha.userservice.data.entity.temp;

import jakarta.persistence.*;

@Entity
@Table(name = "auto_generated")
public class AutoGeneratedEntity {
    /*create table auto_generated (id bigint not null, name varchar(255) not null, primary key (id))
     create sequence auto_generated_seq start with 1 increment by 50*/

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(nullable = false)
    private String name;

    // Constructors, Getters, Setters

    public AutoGeneratedEntity() {}

    public AutoGeneratedEntity(String name) {
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
