package com.fariha.userservice.data.entity.temp;

import jakarta.persistence.*;

@Entity
@Table(name = "identity_generated")
public class IdentityGeneratedEntity {

    /*create table identity_generated (id bigint generated by default as identity, name varchar(255) not null, primary key (id))*/

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String name;

    // Constructors, Getters, Setters

    public IdentityGeneratedEntity() {}

    public IdentityGeneratedEntity(String name) {
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
